### ISSUE TITLE
sublime text 3 JSMT - esformatter-jsx plugin not found

### ISSUE THREAD

**Issue by neosis** [royriojas/esformatter-jsx#102]
Hello

I am using jsfmt package to format jsx file using esformatter-jsx.

I am getting following error -
```
JSFMT ==>
Error: /Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/jsfmt.js:31
        throw err;
        ^

Error: Error: Cannot find plugin 'esformatter-jsx'. Make sure you used the correct name on the config file or run `npm install --save-dev esformatter-jsx` to add it as a project dependency.
    at loadModule (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/esformatter/lib/plugins.js:52:11)
    at /Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/esformatter/lib/plugins.js:42:7
    at Array.forEach (native)
    at loadAndRegister (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/esformatter/lib/plugins.js:39:16)
    at Object.exports.setOptions (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/esformatter/lib/plugins.js:28:3)
    at Object.exports.set (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/esformatter/lib/options.js:51:11)
    at Object.format (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/esformatter/lib/format.js:14:12)
    at Object.exports.format (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/jsfmt/lib/format.js:15:20)
    at /Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/jsfmt.js:25:24
    at Socket.<anonymous> (/Users/neosis/Library/Application Support/Sublime Text 3/Packages/jsfmt/node_modules/get-stdin/index.js:23:3)
```

esformatter and esformatter-jsx node modules are locally installed.
```
_npm ls esformatter esformatter-jsx
learnreactjs@1.0.0 /Users/neosis/Projects/NpmProjects/LearnReactJs
├── esformatter@0.10.0 
└── esformatter-jsx@7.4.1_ 

```

Command line invocation of esformatter with corresponding .esformatter works as expected.

following is my user - jsfmt.sublime-settings. Default settings are unchanged.
```

{
    "autoformat": false,
    "extensions": [
        "js",
        "jsx",
        "sublime-settings"
    ],
    "jsx": {
        "alignWithFirstAttribute": true,
        "attrsOnSameLineAsTag": true,
        "firstAttributeOnSameLine": false,
        "formatJSX": true,
        "maxAttrsOnTag": 1
    },
    "options": { 
        "plugins": [
            "esformatter-jsx",
        ]
    }
}

```

What could be the issue?

Thanks
Ash

**Comment by royriojas** [comment]
hi @neosis can you try the guide shown here? https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

**Comment by neosis** [comment]
Thank you @royriojas. It was my mistake. I installed esformatter and esformatter-jsx in node project directory while I should have installed it in package directory of jsfmt sublime package. It worked now.

best
Ash

**Comment by royriojas** [comment]
cool! @neosis happy formatting :)
