### ISSUE TITLE
 Cannot read property 'formatJSX' of undefined in Sublime Text 2

### ISSUE THREAD

**Issue by kushal** [royriojas/esformatter-jsx#15]
Probably user error, but I'm not sure how to get past this. Thanks!

TypeError: Cannot read property 'formatJSX' of undefined
    at Object.module.exports.stringBefore (/Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/esformatter-jsx/lib/plugin.js:43:24)
    at /Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/lib/plugins.js:78:53
    at Array.reduce (native)
    at Object.pipe (/Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/lib/plugins.js:77:19)
    at Object.stringBefore (/Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/node_modules/mout/function/partial.js:15:22)
    at Object.format (/Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/jsfmt/node_modules/esformatter/lib/esformatter.js:51:17)
    at Object.exports.format (/Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/jsfmt/lib/format.js:15:20)
    at /Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/jsfmt.js:27:24
    at Socket.<anonymous> (/Users/kushal/Library/Application Support/Sublime Text 2/Packages/jsfmt/node_modules/get-stdin/index.js:23:3)
    at Socket.emit (events.js:129:20)

**Comment by royriojas** [comment]
can you provide the version of `esformatter` and `esformatter-jsx` you are using?

**Comment by royriojas** [comment]
It might be that you need to specify the `jsx` section in your `esformatter.json`, check the parameters in the readme

**Comment by kushal** [comment]
esformatter-jsx@.0.10

esformatter@0.7.3

I'm having a hard time sorting out where esformatter.json would even go in
the context of Sublime/jsfmt? I do have a jsx: {} section in
jsfmt.sublime-settings


Thanks!

**Comment by royriojas** [comment]
I'm not familiar with Sublime Text 2, but for the 3 you can do:

```bash
cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/jsfmt/

# the latest version has a bug with formatting some sentences
npm i -D esformatter@0.7.2 

# grab the latest
npm i -D esformatter@latest
```

**Comment by royriojas** [comment]
Oh I just realize you're using an old version of the plugin, the latest one is `esformatter-jsx@2.0.10`

**Comment by kushal** [comment]
Got it, thank you!

**Comment by filipmares** [comment]
Using the latest (2.0.11), but still getting this error.

**Comment by royriojas** [comment]
hi @filipmares, are you using esformatter-jsx from the cli? or are you using it in Sublime Text 3?

If is inside Sublime you might want to follow this guide

https://github.com/royriojas/esformatter-jsx/wiki/Usage-with-jsfmt

You need `esformatter@7` for it to work correctly

**Comment by filipmares** [comment]
@royriojas thank you!
