### ISSUE TITLE
Cannot find plugin 'esformatter-jsx'

### ISSUE THREAD

**Issue by leftstick** [royriojas/esformatter-jsx#31]
The issue happens on my mac. refer to: [issue](https://github.com/sindresorhus/atom-esformatter/issues/29)

Can you help on fixing it?

**Comment by royriojas** [comment]
Let me try, I don't have upgraded yet to "El Capitan"

**Comment by royriojas** [comment]
@leftstick  can you provide a bit more of info about the issue?

And a copy a of a configuration file you're using?

**Comment by royriojas** [comment]
So I traced it to this:

```bash
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Function (native)
    at makePredicate (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1576:10)
    at Object.7 (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1582:6)
    at s (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1:681)
    at /Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1:732
    at Object.13../identifier (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:2273:19)
    at s (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1:681)
    at /Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1:732
    at Object.1../expression (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:47:14)
    at s (/Users/roy/.atom/packages/esformatter/node_modules/esformatter-jsx/node_modules/falafel/node_modules/acorn/dist/acorn.js:1:681)
```

The main problem is that I updated the parser, switched from espree to babel-core to support more ES6/ES7 features that the main `esformatter` plugin not yet support.

Sadly it is failing in the `acorn` module used by `falafel` I will try to make a fix for this today

**Comment by royriojas** [comment]
@leftstick, probably will have to make another patch if the pull request is accepted on `node-falafel` but this should be enough at least it seems to be working for me now. just reinstall `atom-esformatter` or manually install `esformatter-jsx@latest` in your `~/.atom/pacakges/esformatter` folder doing `npm i esformatter@latest`

**Comment by leftstick** [comment]
@royriojas  Really appreciate for your quick fix. It works for me.

**Comment by wtgtybhertgeghgtwtg** [comment]
It looks like the underlying issue [was fixed](https://github.com/ternjs/acorn/commit/aed55f3881beb1ea26d8622ada9973839b2b7175) in `acorn@4.0.3`.  Would updating `acorn` in `falafel` be a better solution?
